/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoJuego;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PantallaJuego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public PantallaJuego() {
        initComponents();
        campoPregunta.setText(juego.establecerPregunta());
        campoOpcion1.setText(juego.establecerOpcion1());
        campoOpcion2.setText(juego.establecerOpcion2());
        campoOpcion3.setText(juego.establecerOpcion3());
        campoOpcion4.setText(juego.establecerOpcion4());
        campoAcumulado.setText(String.valueOf(juego.acumulador()));
        campoPremio.setText(String.valueOf(juego.premio()));
        campoCategoria.setText("Pregunta " + String.valueOf(juego.contador()));
        
    }

    Juego juego = new Juego();
    Pregunta pregunta = new Pregunta();
    Opciones opciones = new Opciones();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        campoCategoria = new javax.swing.JLabel();
        campoPregunta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoOpcion1 = new javax.swing.JRadioButton();
        campoOpcion3 = new javax.swing.JRadioButton();
        campoOpcion2 = new javax.swing.JRadioButton();
        campoOpcion4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        campoAcumulado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoPremio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(481, 395));

        campoCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        campoCategoria.setText("Texto editable n.pregunta");
        campoCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        campoPregunta.setEditable(false);
        campoPregunta.setBackground(new java.awt.Color(0, 51, 102));
        campoPregunta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoPregunta.setForeground(new java.awt.Color(255, 255, 255));
        campoPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPreguntaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Por favor seleccione la respuesta correcta: ");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Enviar respuesta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        campoOpcion1.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(campoOpcion1);
        campoOpcion1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        campoOpcion1.setText("Respuesta editable");
        campoOpcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoOpcion1MouseClicked(evt);
            }
        });
        campoOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOpcion1ActionPerformed(evt);
            }
        });

        campoOpcion3.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(campoOpcion3);
        campoOpcion3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        campoOpcion3.setText("Respuesta editable");
        campoOpcion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoOpcion3MouseClicked(evt);
            }
        });
        campoOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOpcion3ActionPerformed(evt);
            }
        });

        campoOpcion2.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(campoOpcion2);
        campoOpcion2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        campoOpcion2.setText("Respuesta editable");
        campoOpcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoOpcion2MouseClicked(evt);
            }
        });
        campoOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOpcion2ActionPerformed(evt);
            }
        });

        campoOpcion4.setBackground(new java.awt.Color(0, 51, 102));
        buttonGroup1.add(campoOpcion4);
        campoOpcion4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoOpcion4.setForeground(new java.awt.Color(255, 255, 255));
        campoOpcion4.setText("Respuesta editable");
        campoOpcion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoOpcion4MouseClicked(evt);
            }
        });
        campoOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOpcion4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Premio si acierta: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        campoAcumulado.setEditable(false);
        campoAcumulado.setBackground(new java.awt.Color(0, 51, 102));
        campoAcumulado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campoAcumulado.setForeground(new java.awt.Color(255, 255, 255));
        campoAcumulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAcumuladoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Acumulado:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        campoPremio.setEditable(false);
        campoPremio.setBackground(new java.awt.Color(0, 51, 102));
        campoPremio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campoPremio.setForeground(new java.awt.Color(255, 255, 255));
        campoPremio.setText("$ editable");
        campoPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPremioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoAcumulado))
                    .addComponent(campoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoOpcion1)
                            .addComponent(campoOpcion3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoOpcion4)
                                    .addComponent(campoOpcion2))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(campoAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(campoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoOpcion1)
                    .addComponent(campoOpcion2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoOpcion3)
                    .addComponent(campoOpcion4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPreguntaActionPerformed

    private void campoOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOpcion1ActionPerformed

    private void campoOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOpcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOpcion3ActionPerformed

    private void campoOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOpcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOpcion2ActionPerformed

    private void campoOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOpcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOpcion4ActionPerformed

    private void campoAcumuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAcumuladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAcumuladoActionPerformed

    private void campoPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPremioActionPerformed

    private void campoOpcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoOpcion1MouseClicked
        juego.obtenerRespuestaSeleccionada(campoOpcion1.getLabel());
        System.out.println(campoOpcion1.getLabel());
    }//GEN-LAST:event_campoOpcion1MouseClicked

    private void campoOpcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoOpcion2MouseClicked
        juego.obtenerRespuestaSeleccionada(campoOpcion2.getLabel());
        System.out.println(campoOpcion2.getLabel());
    }//GEN-LAST:event_campoOpcion2MouseClicked

    private void campoOpcion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoOpcion3MouseClicked
        juego.obtenerRespuestaSeleccionada(campoOpcion3.getLabel());
        System.out.println(campoOpcion3.getLabel());
    }//GEN-LAST:event_campoOpcion3MouseClicked

    private void campoOpcion4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoOpcion4MouseClicked
        juego.obtenerRespuestaSeleccionada(campoOpcion4.getLabel());
        System.out.println(campoOpcion4.getLabel());
    }//GEN-LAST:event_campoOpcion4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(juego.getRespuestaSeleccionada()== null){
            JOptionPane.showMessageDialog(null, "Seleccione una opcion");
        } else {
           if(juego.getRespuestaSeleccionada() == juego.getRespuestaCorrecta()){
               System.out.println("correcta");
               juego.siguienteNivel();
               juego.iniciarNivel();
               dispose();
           }
           else{
               System.out.println("incorrect");
               juego.terminarJuego("perdida");
               Final final1 = new Final();
               final1.respuestaFinal.setText("¡Respuesta equivocada!");
               dispose();
           }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoAcumulado;
    private javax.swing.JLabel campoCategoria;
    private javax.swing.JRadioButton campoOpcion1;
    private javax.swing.JRadioButton campoOpcion2;
    private javax.swing.JRadioButton campoOpcion3;
    private javax.swing.JRadioButton campoOpcion4;
    private javax.swing.JTextField campoPregunta;
    private javax.swing.JTextField campoPremio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
